cc_library(
    name = "display_h",
    hdrs = ["display.h"],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "system_info_h",
    hdrs = ["system_info.h"],
    visibility = ["//visibility:public"],
)
